#!/usr/bin/env python3
"""Generate crates/sim/src/actor/fields_iw4sp.rs from an installed iw4sp.exe.

usage: scripts/gen-iw4sp-fields.py <path/to/iw4sp.exe> > crates/sim/src/actor/fields_iw4sp.rs

The SP executable keeps its script field tables in .rdata, each ended by a null
name. Actor fields are 40-byte entries (name, offset, fieldtype, setter, getter);
entity and sentient fields are 32-byte entries (name, offset:u32 + fieldtype:u32,
setter, getter). The setter shared by most entries is the read-only refusal.
"""
import re
import struct
import sys

MIN_TABLE = 8
# anchor (first entry) -> (stride, table name)
TABLES = {
    "type": (40, "ACTOR"),
    "team": (32, "SENTIENT"),
    "code_classname": (32, "ENTITY"),
}
FIELD_TYPES = {
    0: "Int",
    1: "Short",
    2: "Byte",
    3: "Float",
    4: "String",
    5: "CString",
    6: "Vector",
    7: "Entity",
    8: "EntHandle",
    9: "Angle",
    10: "ActorHandle",
    11: "SentientHandle",
    12: "Time",
    13: "PathNode",
    14: "Object",
    15: "Model",
}


def sections(d):
    pe = struct.unpack_from("<I", d, 0x3C)[0]
    count = struct.unpack_from("<H", d, pe + 6)[0]
    opt = struct.unpack_from("<H", d, pe + 20)[0]
    base = struct.unpack_from("<Q", d, pe + 48)[0]
    out = {}
    for i in range(count):
        o = pe + 24 + opt + 40 * i
        name = d[o : o + 8].rstrip(b"\0").decode()
        vsize, va, rsize, raw = struct.unpack_from("<IIII", d, o + 8)
        out[name] = (va, max(vsize, rsize), raw, rsize)
    return base, out


def tables(d):
    base, secs = sections(d)
    rd_va, rd_size, rd_raw, rd_rsize = secs[".rdata"]
    tx_va, tx_size, _, _ = secs[".text"]

    def name_at(v):
        r = v - base
        if not rd_va <= r < rd_va + rd_size:
            return None
        off = rd_raw + r - rd_va
        end = d.find(b"\0", off, off + 64)
        s = d[off:end] if end > off else b""
        return s.decode() if re.fullmatch(rb"[a-z_][a-z0-9_]*", s) else None

    def code(v):
        return v == 0 or tx_va <= v - base < tx_va + tx_size

    def entry(o, stride):
        if stride == 40:
            name, ofs, kind, setter, getter = struct.unpack_from("<QQQQQ", d, o)
        else:
            name, ofs, kind, setter, getter = struct.unpack_from("<QIIQQ", d, o)
        name = name_at(name)
        if name is None or ofs > 0x10000 or kind not in FIELD_TYPES:
            return None
        if not code(setter) or not code(getter):
            return None
        return name, ofs, kind, setter, getter

    for stride in (40, 32):
        i = rd_raw
        while i + stride <= rd_raw + rd_rsize:
            run, j = [], i
            while (e := entry(j, stride)) is not None:
                run.append(e)
                j += stride
            if len(run) >= MIN_TABLE:
                yield stride, run
                i = j
            else:
                i += 8


def main():
    d = open(sys.argv[1], "rb").read()
    found = {}
    for stride, run in tables(d):
        anchor = TABLES.get(run[0][0])
        if anchor and anchor[0] == stride:
            found.setdefault(anchor[1], run)
    missing = {name for _, name in TABLES.values()} - set(found)
    if missing:
        sys.exit(f"field tables not found: {sorted(missing)}")
    setters = {}
    for run in found.values():
        for _, _, _, setter, _ in run:
            if setter:
                setters[setter] = setters.get(setter, 0) + 1
    read_only = max(setters, key=setters.get)
    print("// @generated by scripts/gen-iw4sp-fields.py; do not edit.")
    print("use super::fields::{FieldDef, FieldType::*};")
    for _, table in TABLES.values():
        print()
        print(f"pub(crate) const IW4SP_{table}_FIELDS: &[FieldDef] = &[")
        for name, ofs, kind, setter, getter in found[table]:
            ro = str(setter == read_only).lower()
            custom = str(bool(getter) or (bool(setter) and setter != read_only)).lower()
            print(
                f'    FieldDef::new("{name}", {ofs:#x}, {FIELD_TYPES[kind]}, {ro}, {custom}),'
            )
        print("];")


if __name__ == "__main__":
    main()
