#!/usr/bin/env python3
"""Generate crates/sim/src/script/profile/iw4sp_catalog.rs from an installed iw4sp.exe.

usage: scripts/gen-iw4sp-catalog.py <path/to/iw4sp.exe> > crates/sim/src/script/profile/iw4sp_catalog.rs
"""
import re
import struct
import sys

ENTRY = 24
OWNER_BY_ANCHOR = {
    "startscriptedanim": ("Method", "Actor"),
    "getenemysqdist": ("Method", "Actor"),
    "getviewmodel": ("Method", "Player"),
    "buttonpressed": ("Method", "Player"),
    "settext": ("Method", "HudElem"),
    "animscripted": ("Method", "Entity"),
    "attach": ("Method", "Entity"),
    "startignoringspotlight": ("Method", "Entity"),
    "moveto": ("Method", "ScriptMover"),
    "vehicle_teleport": ("Method", "Vehicle"),
    "createprintchannel": ("Function", "Script"),
    "iprintln": ("Function", "Script"),
    "objective_add": ("Function", "Script"),
}


def sections(d):
    pe = struct.unpack_from("<I", d, 0x3C)[0]
    count = struct.unpack_from("<H", d, pe + 6)[0]
    opt = struct.unpack_from("<H", d, pe + 20)[0]
    base = struct.unpack_from("<Q", d, pe + 48)[0]
    out = []
    for i in range(count):
        o = pe + 24 + opt + 40 * i
        name = d[o : o + 8].rstrip(b"\0").decode()
        vsize, va, rsize, raw = struct.unpack_from("<IIII", d, o + 8)
        out.append((name, va, max(vsize, rsize), raw, rsize))
    return base, out


def tables(d):
    base, secs = sections(d)

    def locate(v):
        r = v - base
        for name, va, size, raw, _ in secs:
            if va <= r < va + size:
                return name, raw + (r - va)
        return None, None

    def name_at(v):
        sec, off = locate(v)
        if sec != ".rdata":
            return None
        end = d.find(b"\0", off, off + 64)
        s = d[off:end] if end > off else b""
        return s.decode() if re.fullmatch(rb"[a-z_][a-z0-9_]*", s) else None

    for sec, _, _, raw, rsize in secs:
        if sec not in (".data", ".rdata"):
            continue
        i = raw
        while i + ENTRY <= raw + rsize:
            run, j = [], i
            while j + ENTRY <= raw + rsize:
                p, f, dev, _ = struct.unpack_from("<QQII", d, j)
                name = name_at(p)
                if name is None or dev not in (0, 1) or locate(f)[0] not in (".text", ".bind"):
                    break
                run.append((name, bool(dev)))
                j += ENTRY
            if len(run) >= 8:
                yield run
                i = j
            else:
                i += 8


def main():
    d = open(sys.argv[1], "rb").read()
    rows = {}
    for run in tables(d):
        anchor = run[0][0]
        if anchor not in OWNER_BY_ANCHOR:
            sys.exit(f"unrecognised builtin table starting at `{anchor}` ({len(run)} entries)")
        namespace, owner = OWNER_BY_ANCHOR[anchor]
        for name, dev in run:
            rows.setdefault((namespace, name), (owner, dev))
    missing = set(OWNER_BY_ANCHOR) - {name for _, name in rows}
    if missing:
        sys.exit(f"tables not found: {sorted(missing)}")
    print("// @generated by scripts/gen-iw4sp-catalog.py; do not edit.")
    print("use super::catalog::{Builtin, Namespace::*, Owner::*};")
    print()
    print("pub(super) const IW4SP: &[Builtin] = &[")
    for (namespace, name), (owner, dev) in sorted(rows.items()):
        print(f'    Builtin::new({namespace}, "{name}", {owner}, {str(dev).lower()}),')
    print("];")


if __name__ == "__main__":
    main()
